on: [push, pull_request]

name: reprex

jobs:
  reprex:
    runs-on: ubuntu-16.04
    steps:
      - name: Try to install ZeroMQ
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install libzmq3-dev
