on: [push, pull_request]
name: reprex
jobs:
  reprex:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-18.04}
          - {os: ubuntu-20.04}
    steps:
      - name: Try to install ZeroMQ
        run: sudo apt-get install libzmq3-dev
